### ISSUE TITLE
`pg_isready` issues on minishift (1.4.1 with openshift 3.6.0)

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-dependency-wait-service#3]
The current use of `pg_isready` doesn't seem to work on minishift 1.4.1 with openshift 3.6.0. 

Its very wacky and I don't understand this at all.

By shelling into the keycloak-db or wit-db pods via  `oc exec -it podName bash` we can run `pg_isready`. 

What I found was that from each pod (e.g. keycloak-db) we can invoke the other service but not its own service name/service ip.

e.g.

```
oc exec -it keycloak-db-1234 bash
# this fails
pg_isready -h keycloak-db 
# this works
pg_isready -h wit-db 
```
```
oc exec -it wit-db-4567 bash
# this works
pg_isready -h keycloak-db 
# this fails
pg_isready -h wit-db 
```
I even had issues accessing the pod ip too. So there's something quite broken about `pg_isready` on minishift and it doesn't work inside the init-container either. However it all works perfectly on kubernetes.

I guess on openshift we may need to do something different like a basic ping? 

Actually OpenShift is using `pg_isready` as a readiness check anyway inside the postgres services; so being able to open a socket on the service name/IP address might be a good enough way to check if postgres is up? Or maybe we just query the kubernetes API for at least one endpoint for the Service - rather than talking to it? Pinging it only checks there's a valid IP address - which there will be whether or not there's a ready pod - so maybe if opening a socket isn't a good enough check we need to query DNS for an endpoint or use the kubernetes REST API?

**Comment by jstrachan** [comment]
maybe using a DNS query to find SRV records to find ready endpoints https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ is the best way to deal with service dependencies which are not http based? Then we don't need to use ServiceAccounts + roles to query the kubernetes REST API and it can work for any kind of service

**Comment by jstrachan** [comment]
ah - DNS only has multiple records for each endpoint when using headless services I think
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

so we're maybe back to either trying to open the socket (though the kube proxy might allow a socket to be opened without a backing pod - we'd have to test that?) - or querying the kubernetes service endpoints

**Comment by jstrachan** [comment]
ok another idea ;) - we could have a separate microservice - like https://github.com/fabric8io/exposecontroller/ - lets call it the `readycontroller` that has a simple REST API that the init-container can curl which returns a 200 if a given service has at least one ready endpoint.

So the existing dependency-wait-service could invoke something like:

```
dependency-wait-service http://readycontroller/keycloak-db/
```

Then we've a single microservice (Deployment + Service), `readycontroller` that uses the kubernetes REST API to check if a given service name has a valid endpoint or not - which is one place to setup a ServiceAccount & Role and keeps the `dependency-wait-service` init container nice and simple

**Comment by sathishvj** [comment]
This has been resolved differently by passing the username to the postgres db. 
https://github.com/fabric8-services/fabric8-dependency-wait-service/commit/3496ac240111b79fafc212d76a14008b5e3d9f7c
